version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bd2_labs_image
    container_name: bd2_labs_host
    tty: true
    working_dir: /var/www/bd2_labs
    volumes:
      - ./:/var/www/bd2_labs
    ports:
      - 8000:8000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge